import type { Metadata } from 'next'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className=' mx-auto max-w-4xl h-full w-full'>
        {children} 
    </div>
  )
}
